import { GameStats, LifeEvent, LifeStatusConditions, PlayerFlags } from '@/types/game';

type EventSpec = {
  id: string;
  stageId: string;
  title: string;
  description: string;
  conditions?: Partial<PlayerFlags>;
  anyConditions?: Partial<PlayerFlags>[];
  lifeStatusConditions?: LifeStatusConditions;
  left: {
    label: string;
    description: string;
    effects: Partial<GameStats>;
    stateEffects?: Partial<PlayerFlags>;
    lifeStatusEffects?: LifeEvent['choices'][number]['lifeStatusEffects'];
  };
  right: {
    label: string;
    description: string;
    effects: Partial<GameStats>;
    stateEffects?: Partial<PlayerFlags>;
    lifeStatusEffects?: LifeEvent['choices'][number]['lifeStatusEffects'];
  };
};

const specs: EventSpec[] = [
  {
    id: 'status_1_club_invite',
    stageId: 'stage_1',
    title: '放課後に誘われる',
    description: '友人から最後に寄り道しようと言われた。',
    left: { label: '行く', description: '少しだけ顔を出す。', effects: { relationshipCapital: 3, freedom: -1 }, stateEffects: { hasOldFriends: true } },
    right: { label: '帰る', description: '明日の準備を優先する。', effects: { career: 2, relationshipCapital: -1 } },
  },
  {
    id: 'status_1_parent_talk',
    stageId: 'stage_1',
    title: '親に進路を聞かれる',
    description: '夕食中、これからどうするのか聞かれた。',
    left: { label: '話す', description: '迷いも含めて話す。', effects: { emergencySupport: 2, meaningCapital: 2 }, stateEffects: { familyOriented: true } },
    right: { label: '濁す', description: 'まだ言えないと避ける。', effects: { freedom: 2, emergencySupport: -1 } },
  },
  {
    id: 'status_1_part_time',
    stageId: 'stage_1',
    title: '初めてのバイト',
    description: '近所の店から週末だけ来ないかと言われる。',
    left: { label: '働く', description: '短時間から始める。', effects: { money: 3, relationshipCapital: 2 }, lifeStatusEffects: { jobStatus: 'employee' } },
    right: { label: '断る', description: '今は休みを守る。', effects: { freedom: 3, money: -1 } },
  },
  {
    id: 'status_1_move_room',
    stageId: 'stage_1',
    title: '一人暮らしを考える',
    description: '進学先の近くに部屋を借りる話が出た。',
    left: { label: '借りる', description: '自分の生活を始める。', effects: { freedom: 4, money: -3, emergencySupport: -1 }, lifeStatusEffects: { housingStatus: 'alone' } },
    right: { label: '実家に残る', description: '通える範囲で暮らす。', effects: { money: 2, emergencySupport: 2, freedom: -2 }, lifeStatusEffects: { housingStatus: 'withParents' } },
  },
  {
    id: 'status_2_work_lunch',
    stageId: 'stage_2',
    title: '昼休みに誘われる',
    description: '同期が近くの店へ行こうと声をかけてきた。',
    left: { label: '一緒に行く', description: '短い雑談をする。', effects: { relationshipCapital: 3, career: 1, money: -1 } },
    right: { label: '一人で食べる', description: '静かな時間を取る。', effects: { freedom: 2, relationshipCapital: -1 } },
  },
  {
    id: 'status_2_online_group',
    stageId: 'stage_2',
    title: '趣味の募集を見る',
    description: 'オンラインの作業会が今夜ある。',
    left: { label: '参加する', description: '音声だけで入る。', effects: { outsideWorkBelonging: 3, relationshipCapital: 2 }, stateEffects: { joinedHobbyCommunity: true } },
    right: { label: '見るだけ', description: '投稿だけ眺める。', effects: { freedom: 2, outsideWorkBelonging: -1 } },
  },
  {
    id: 'status_2_salary_call',
    stageId: 'stage_2',
    title: '家族から電話',
    description: '初任給の後、親から元気かと電話が来た。',
    left: { label: '折り返す', description: '五分だけ話す。', effects: { emergencySupport: 2, meaningCapital: 1 }, stateEffects: { familyOriented: true } },
    right: { label: '後回し', description: '通知だけ閉じる。', effects: { freedom: 2, emergencySupport: -1 } },
  },
  {
    id: 'status_2_neighbor_greet',
    stageId: 'stage_2',
    title: '隣人と鉢合わせる',
    description: 'ゴミ出しで同じ階の人と目が合った。',
    left: { label: '挨拶する', description: '軽く会釈する。', effects: { relationshipCapital: 2, emergencySupport: 1 }, stateEffects: { hasTrustedNeighbor: true }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '通り過ぎる', description: '急いでいるふりをする。', effects: { freedom: 1, relationshipCapital: -1 } },
  },
  {
    id: 'status_3_friend_dm',
    stageId: 'stage_3',
    title: '友人からDM',
    description: '久しぶりに飲まないかと連絡が来た。',
    left: { label: '返す', description: '候補日を一つ出す。', effects: { relationshipCapital: 4, emergencySupport: 2, money: -1 }, stateEffects: { hasOldFriends: true } },
    right: { label: '流す', description: '既読のままにする。', effects: { freedom: 2, relationshipCapital: -2 }, stateEffects: { lostOldFriends: true } },
  },
  {
    id: 'status_3_training',
    stageId: 'stage_3',
    title: '研修の案内',
    description: '会社から社外研修に行かないかと言われる。',
    lifeStatusConditions: { jobStatus: ['employee', 'manager'] },
    left: { label: '行く', description: '半日だけ参加する。', effects: { career: 4, relationshipCapital: 1, freedom: -1 } },
    right: { label: '断る', description: '通常業務を優先する。', effects: { career: 1, freedom: 2 } },
  },
  {
    id: 'status_3_partner_budget',
    stageId: 'stage_3',
    title: '将来のお金の話',
    description: '恋人と家賃や貯金の話になった。',
    lifeStatusConditions: { maritalStatus: ['dating'] },
    left: { label: '一緒に見る', description: '家計アプリを開く。', effects: { familyCapital: 3, emergencySupport: 2, money: 1 } },
    right: { label: '避ける', description: 'また今度にする。', effects: { freedom: 2, familyCapital: -2 } },
  },
  {
    id: 'status_3_local_class',
    stageId: 'stage_3',
    title: '市民講座を見つける',
    description: '週末の料理講座が空いている。',
    left: { label: '申し込む', description: '一回だけ試す。', effects: { outsideWorkBelonging: 3, relationshipCapital: 2, money: -1 }, stateEffects: { communityActive: true }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '閉じる', description: '予定を入れない。', effects: { freedom: 2, outsideWorkBelonging: -1 } },
  },
  {
    id: 'status_4_ring_shop',
    stageId: 'stage_4',
    title: '指輪の店の前',
    description: 'パートナーと歩いていて、ふと足が止まった。',
    lifeStatusConditions: { maritalStatus: ['dating'] },
    left: { label: '話題にする', description: '将来の話を少しする。', effects: { familyCapital: 4, meaningCapital: 2, freedom: -1 }, lifeStatusEffects: { maritalStatus: 'married', housingStatus: 'withPartner', hasEmergencyContact: true } },
    right: { label: '通り過ぎる', description: '何も言わない。', effects: { freedom: 2, familyCapital: -2 } },
  },
  {
    id: 'status_4_work_offer',
    stageId: 'stage_4',
    title: '独立の誘い',
    description: '知人から一緒に事業をやらないかと言われた。',
    lifeStatusConditions: { jobStatus: ['employee', 'manager', 'freelance'] },
    left: { label: '乗る', description: '小さく始める。', effects: { career: 5, money: -3, health: -2 }, stateEffects: { workIdentityDependent: true }, lifeStatusEffects: { jobStatus: 'owner' } },
    right: { label: '残る', description: '今の仕事を続ける。', effects: { money: 2, health: 1, career: -1 }, lifeStatusEffects: { jobStatus: 'employee' } },
  },
  {
    id: 'status_4_share_living',
    stageId: 'stage_4',
    title: '共同住まいの話',
    description: '友人が空き部屋を紹介してくれた。',
    lifeStatusConditions: { maritalStatus: ['single', 'dating'] },
    left: { label: '見に行く', description: '住人に会ってみる。', effects: { relationshipCapital: 3, money: 2, freedom: -2 }, lifeStatusEffects: { housingStatus: 'shared', hasLocalCommunity: true } },
    right: { label: '一人で住む', description: '今の部屋を守る。', effects: { freedom: 3, emergencySupport: -1 }, lifeStatusEffects: { housingStatus: 'alone' } },
  },
  {
    id: 'status_4_parent_photo',
    stageId: 'stage_4',
    title: '実家から写真',
    description: '親が庭の写真を送ってきた。',
    left: { label: '返事する', description: '近況を一言返す。', effects: { emergencySupport: 2, meaningCapital: 1 }, stateEffects: { familyOriented: true } },
    right: { label: '既読だけ', description: '忙しくて閉じる。', effects: { career: 1, emergencySupport: -1 } },
  },
  {
    id: 'status_5_child_notice',
    stageId: 'stage_5',
    title: '保育園の掲示',
    description: '行事の手伝い募集が出ている。',
    lifeStatusConditions: { childrenCountMin: 1 },
    left: { label: '手伝う', description: '短い役割を受ける。', effects: { nextGeneration: 4, relationshipCapital: 2, freedom: -2 }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '任せる', description: '今回は見送る。', effects: { career: 1, nextGeneration: -2 } },
  },
  {
    id: 'status_5_no_child_mentee',
    stageId: 'stage_5',
    title: '後輩に相談される',
    description: '若い同僚が仕事の悩みを話してきた。',
    lifeStatusConditions: { childrenCount: 0 },
    left: { label: '聞く', description: '十五分だけ時間を取る。', effects: { nextGeneration: 4, meaningCapital: 2 }, stateEffects: { hasIntergenerationalContact: true } },
    right: { label: '急ぐ', description: '今は忙しいと断る。', effects: { career: 2, nextGeneration: -2 } },
  },
  {
    id: 'status_5_manager_team',
    stageId: 'stage_5',
    title: '部下が沈んでいる',
    description: '会議後、若手の表情が暗い。',
    lifeStatusConditions: { jobStatus: ['manager', 'executive', 'owner'] },
    left: { label: '声をかける', description: '帰り際に聞く。', effects: { relationshipCapital: 3, career: 1, freedom: -1 } },
    right: { label: '見送る', description: '自分の仕事に戻る。', effects: { career: 2, relationshipCapital: -2 } },
  },
  {
    id: 'status_5_health_check',
    stageId: 'stage_5',
    title: '健診の通知',
    description: '会社から健康診断の案内が届く。',
    left: { label: '予約する', description: '午前の枠を取る。', effects: { health: 4, money: -1 } },
    right: { label: '後回し', description: '忙しくて閉じる。', effects: { career: 1, health: -2 } },
  },
  {
    id: 'status_6_reunion_photo',
    stageId: 'stage_6',
    title: '同窓会の写真',
    description: '昔の友人たちの写真が流れてきた。',
    anyConditions: [{ hasOldFriends: true }, { keptSchoolFriends: true }],
    left: { label: '反応する', description: '懐かしいと送る。', effects: { relationshipCapital: 4, emergencySupport: 2 }, stateEffects: { reconnectedOldFriend: true } },
    right: { label: '閉じる', description: '何も押さない。', effects: { freedom: 2, relationshipCapital: -2 } },
  },
  {
    id: 'status_6_spouse_walk',
    stageId: 'stage_6',
    title: '夜の散歩',
    description: '配偶者から少し歩こうと言われた。',
    lifeStatusConditions: { maritalStatus: ['married'] },
    left: { label: '歩く', description: '十分だけ外へ出る。', effects: { familyCapital: 3, health: 2, freedom: -1 } },
    right: { label: '断る', description: '疲れたと返す。', effects: { freedom: 2, familyCapital: -2 } },
  },
  {
    id: 'status_6_owner_hiring',
    stageId: 'stage_6',
    title: '人を雇うか迷う',
    description: '仕事が増え、一人では回りにくい。',
    lifeStatusConditions: { jobStatus: ['owner'] },
    left: { label: '頼む', description: '小さく外注する。', effects: { career: 3, relationshipCapital: 2, money: -3 } },
    right: { label: '抱える', description: '自分で処理する。', effects: { money: 2, health: -4 }, stateEffects: { workIdentityDependent: true } },
  },
  {
    id: 'status_6_solo_trip',
    stageId: 'stage_6',
    title: '一人旅の朝',
    description: '旅先で誰かに写真を送るか迷う。',
    lifeStatusConditions: { housingStatus: ['alone', 'shared'] },
    left: { label: '送る', description: '一枚だけ共有する。', effects: { relationshipCapital: 2, meaningCapital: 2 } },
    right: { label: 'しまう', description: '自分だけで楽しむ。', effects: { freedom: 3, relationshipCapital: -1 } },
  },
  {
    id: 'status_7_parent_forms',
    stageId: 'stage_7',
    title: '親の書類',
    description: '介護保険の封筒が実家に届いた。',
    left: { label: '一緒に見る', description: '電話で内容を確認する。', effects: { emergencySupport: 3, meaningCapital: 2, freedom: -1 }, stateEffects: { caregiverExperience: true } },
    right: { label: '任せる', description: '本人に任せる。', effects: { freedom: 2, emergencySupport: -2 } },
  },
  {
    id: 'status_7_child_silence',
    stageId: 'stage_7',
    title: '子どもが黙る',
    description: '食卓で子どもの口数が少ない。',
    lifeStatusConditions: { childrenCountMin: 1 },
    left: { label: '聞く', description: '急かさず待つ。', effects: { familyCapital: 4, nextGeneration: 3 } },
    right: { label: '流す', description: '疲れているだけと思う。', effects: { freedom: 1, familyCapital: -3 }, stateEffects: { familyPresentButDistant: true } },
  },
  {
    id: 'status_7_local_notice',
    stageId: 'stage_7',
    title: '防災訓練の案内',
    description: 'マンション掲示板に訓練のお知らせがある。',
    left: { label: '出る', description: '顔を出してみる。', effects: { emergencySupport: 3, relationshipCapital: 2 }, stateEffects: { hasTrustedNeighbor: true }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '出ない', description: '予定を入れない。', effects: { freedom: 2, emergencySupport: -1 } },
  },
  {
    id: 'status_7_body_signal',
    stageId: 'stage_7',
    title: '肩こりが抜けない',
    description: '朝から体が重い日が続く。',
    left: { label: '受診する', description: '早めに相談する。', effects: { health: 4, money: -1 }, stateEffects: { usesSupportServices: true } },
    right: { label: '我慢する', description: '仕事で紛らわせる。', effects: { career: 2, health: -3 } },
  },
  {
    id: 'status_8_old_friend_calendar',
    stageId: 'stage_8',
    title: '友人との定例',
    description: '月一の予定を固定しないかと言われた。',
    left: { label: '固定する', description: '第2土曜に入れる。', effects: { relationshipCapital: 4, emergencySupport: 2, freedom: -1 }, stateEffects: { hasOldFriends: true } },
    right: { label: '都度にする', description: '予定は決めない。', effects: { freedom: 2, relationshipCapital: -1 } },
  },
  {
    id: 'status_8_child_money',
    stageId: 'stage_8',
    title: '子どもの出費',
    description: '子どもから急な費用の相談が来た。',
    lifeStatusConditions: { childrenCountMin: 1 },
    left: { label: '一緒に考える', description: '金額と理由を聞く。', effects: { familyCapital: 3, nextGeneration: 3, money: -2 } },
    right: { label: '断る', description: '自分で何とかしてと言う。', effects: { money: 2, familyCapital: -3 } },
  },
  {
    id: 'status_8_manager_exit',
    stageId: 'stage_8',
    title: '部下が辞めたいと言う',
    description: '面談で退職の相談を受けた。',
    lifeStatusConditions: { jobStatus: ['manager', 'executive', 'owner'] },
    left: { label: '理由を聞く', description: '引き止める前に聞く。', effects: { relationshipCapital: 3, career: 1, health: -1 } },
    right: { label: '説得する', description: 'すぐ残るよう話す。', effects: { career: 2, relationshipCapital: -2 } },
  },
  {
    id: 'status_8_home_repair',
    stageId: 'stage_8',
    title: '家の修理',
    description: '水回りの小さな不具合が出た。',
    left: { label: '業者を呼ぶ', description: '早めに直す。', effects: { health: 2, money: -3, emergencySupport: 1 } },
    right: { label: '放置する', description: 'まだ使えると見る。', effects: { money: 2, health: -1 } },
  },
  {
    id: 'status_9_spouse_checkup',
    stageId: 'stage_9',
    title: '配偶者の検査',
    description: '再検査の予約日が近づく。',
    lifeStatusConditions: { maritalStatus: ['married'] },
    left: { label: '付き添う', description: '予定を空ける。', effects: { familyCapital: 5, emergencySupport: 2, freedom: -2 }, stateEffects: { partnerCareExperience: true } },
    right: { label: '任せる', description: '本人に任せる。', effects: { freedom: 2, familyCapital: -3 } },
  },
  {
    id: 'status_9_empty_room',
    stageId: 'stage_9',
    title: '空いた部屋',
    description: '子どもの部屋が物置になっている。',
    lifeStatusConditions: { childrenCountMin: 1 },
    left: { label: '整える', description: '帰れる場所として残す。', effects: { familyCapital: 3, nextGeneration: 2, freedom: -1 } },
    right: { label: '片づける', description: '自分の部屋に変える。', effects: { freedom: 3, familyCapital: -1 } },
  },
  {
    id: 'status_9_solo_meal',
    stageId: 'stage_9',
    title: '一人の夕食',
    description: '今日も誰とも話さず夕方になった。',
    lifeStatusConditions: { housingStatus: ['alone'] },
    left: { label: '外で食べる', description: '近所の店に行く。', effects: { relationshipCapital: 3, outsideWorkBelonging: 2, money: -2 }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '家で済ます', description: '静かに食べる。', effects: { freedom: 2, relationshipCapital: -2 } },
  },
  {
    id: 'status_9_retire_plan',
    stageId: 'stage_9',
    title: '退職後の予定',
    description: '会社から再雇用の希望を聞かれた。',
    lifeStatusConditions: { jobStatus: ['employee', 'manager', 'executive'] },
    left: { label: '働き続ける', description: '週3で残る。', effects: { money: 4, career: 2, freedom: -3 }, lifeStatusEffects: { jobStatus: 'employee' } },
    right: { label: '退職する', description: '仕事を一区切りにする。', effects: { freedom: 5, career: -2 }, lifeStatusEffects: { jobStatus: 'retired' } },
  },
  {
    id: 'status_10_first_week',
    stageId: 'stage_10',
    title: '退職後の初週',
    description: '曜日の感覚が薄くなってきた。',
    lifeStatusConditions: { jobStatus: ['retired'] },
    left: { label: '予定を入れる', description: '週一の外出を決める。', effects: { outsideWorkBelonging: 4, health: 2 }, stateEffects: { choseSolitudeWithStructure: true } },
    right: { label: '流れに任せる', description: '何も決めない。', effects: { freedom: 3, outsideWorkBelonging: -3 } },
  },
  {
    id: 'status_10_community_help',
    stageId: 'stage_10',
    title: '地域で頼まれる',
    description: '掲示物の貼り替えを手伝えないかと言われた。',
    lifeStatusConditions: { hasLocalCommunity: true },
    left: { label: '手伝う', description: '三十分だけ出る。', effects: { outsideWorkBelonging: 3, relationshipCapital: 2, freedom: -1 }, stateEffects: { hasTrustedNeighbor: true } },
    right: { label: '断る', description: '今日は出ない。', effects: { freedom: 2, outsideWorkBelonging: -2 } },
  },
  {
    id: 'status_10_owner_successor',
    stageId: 'stage_10',
    title: '事業の引き際',
    description: '続けるか誰かに任せるか考える。',
    lifeStatusConditions: { jobStatus: ['owner'] },
    left: { label: '任せる', description: '若手に一部渡す。', effects: { nextGeneration: 4, health: 2, career: -1 }, stateEffects: { hasIntergenerationalContact: true } },
    right: { label: '続ける', description: 'まだ自分で見る。', effects: { career: 4, health: -3 }, stateEffects: { workIdentityDependent: true } },
  },
  {
    id: 'status_10_partner_trip',
    stageId: 'stage_10',
    title: '小旅行の誘い',
    description: '配偶者から一泊で出かけようと言われた。',
    lifeStatusConditions: { maritalStatus: ['married'] },
    left: { label: '行く', description: '近場で計画する。', effects: { familyCapital: 4, meaningCapital: 2, money: -3 } },
    right: { label: 'やめる', description: '疲れるから断る。', effects: { freedom: 2, familyCapital: -3 } },
  },
  {
    id: 'status_11_emergency_note',
    stageId: 'stage_11',
    title: '連絡先メモ',
    description: '冷蔵庫に緊急連絡先を貼るか迷う。',
    left: { label: '貼る', description: '二人分を書いておく。', effects: { emergencySupport: 5, freedom: -1 }, lifeStatusEffects: { hasEmergencyContact: true } },
    right: { label: '貼らない', description: 'まだ大丈夫と思う。', effects: { freedom: 2, emergencySupport: -3 }, lifeStatusEffects: { hasEmergencyContact: false } },
  },
  {
    id: 'status_11_morning_place',
    stageId: 'stage_11',
    title: '朝の行き先',
    description: '起きても予定がない。',
    left: { label: '外へ出る', description: '同じ店に寄る。', effects: { outsideWorkBelonging: 4, health: 2, relationshipCapital: 2 }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '家にいる', description: 'テレビをつける。', effects: { freedom: 2, outsideWorkBelonging: -3 } },
  },
  {
    id: 'status_11_child_call',
    stageId: 'stage_11',
    title: '子どもに電話',
    description: '用事はないが声を聞きたい。',
    lifeStatusConditions: { childrenCountMin: 1 },
    left: { label: '短くかける', description: '三分だけ話す。', effects: { familyCapital: 4, nextGeneration: 3, emergencySupport: 1 } },
    right: { label: 'やめる', description: '迷惑かと閉じる。', effects: { freedom: 1, familyCapital: -2 } },
  },
  {
    id: 'status_11_public_counter',
    stageId: 'stage_11',
    title: '支援窓口の前',
    description: '役所で見守りサービスの案内を見た。',
    left: { label: '聞く', description: '資料をもらう。', effects: { emergencySupport: 4, meaningCapital: 1 }, stateEffects: { usesSupportServices: true }, lifeStatusEffects: { hasEmergencyContact: true } },
    right: { label: '通る', description: 'まだ早いと思う。', effects: { freedom: 2, emergencySupport: -2 } },
  },
  {
    id: 'status_12_doorbell',
    stageId: 'stage_12',
    title: 'インターホンが鳴る',
    description: '近所の人が回覧板を持ってきた。',
    left: { label: '話す', description: '体調も一言伝える。', effects: { relationshipCapital: 3, emergencySupport: 3 }, stateEffects: { hasTrustedNeighbor: true }, lifeStatusEffects: { hasLocalCommunity: true } },
    right: { label: '受け取るだけ', description: 'すぐ扉を閉める。', effects: { freedom: 1, relationshipCapital: -1 } },
  },
  {
    id: 'status_12_phone_battery',
    stageId: 'stage_12',
    title: 'スマホの電池',
    description: '外出前、充電が残り10%しかない。',
    left: { label: '充電する', description: '出発を少し遅らせる。', effects: { emergencySupport: 3, freedom: -1 } },
    right: { label: 'そのまま出る', description: '近くだから大丈夫と思う。', effects: { freedom: 2, emergencySupport: -3 } },
  },
  {
    id: 'status_12_final_message',
    stageId: 'stage_12',
    title: '最後に一通送る',
    description: 'ふと、誰かに近況を送りたくなった。',
    left: { label: '送る', description: '元気？と短く送る。', effects: { relationshipCapital: 4, emergencySupport: 2 }, stateEffects: { reconnectedOldFriend: true } },
    right: { label: 'しまう', description: '画面を閉じる。', effects: { freedom: 1, relationshipCapital: -2 } },
  },
  {
    id: 'status_12_support_card',
    stageId: 'stage_12',
    title: '支援カードを書く',
    description: '財布に入れる緊急カードを作れる。',
    left: { label: '書く', description: '連絡先と病歴を書く。', effects: { emergencySupport: 6, freedom: -1 }, lifeStatusEffects: { hasEmergencyContact: true } },
    right: { label: '書かない', description: '面倒でやめる。', effects: { freedom: 2, emergencySupport: -4 }, lifeStatusEffects: { hasEmergencyContact: false } },
  },
];

export const statusEvents: LifeEvent[] = specs.map((spec) => ({
  id: spec.id,
  stageId: spec.stageId,
  title: spec.title,
  description: spec.description,
  conditions: spec.conditions,
  anyConditions: spec.anyConditions,
  lifeStatusConditions: spec.lifeStatusConditions,
  choices: [
    {
      id: `${spec.id}_left`,
      label: spec.left.label,
      description: spec.left.description,
      feedback: `${spec.left.label}を選びました。`,
      effects: spec.left.effects,
      stateEffects: spec.left.stateEffects,
      lifeStatusEffects: spec.left.lifeStatusEffects,
    },
    {
      id: `${spec.id}_right`,
      label: spec.right.label,
      description: spec.right.description,
      feedback: `${spec.right.label}を選びました。`,
      effects: spec.right.effects,
      stateEffects: spec.right.stateEffects,
      lifeStatusEffects: spec.right.lifeStatusEffects,
    },
  ],
}));
